// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:编号" json:"id"`              // 编号
	UserName    string    `gorm:"column:user_name;not null;comment:呢称" json:"user_name"`                     // 呢称
	Email       string    `gorm:"column:email;not null;comment:邮件，用于登录" json:"email"`                        // 邮件，用于登录
	Password    string    `gorm:"column:password;not null;comment:用户密码（密码规则：MD5+GENEZ+MD5）" json:"password"` // 用户密码（密码规则：MD5+GENEZ+MD5）
	Avatar      string    `gorm:"column:avatar;comment:头像地址" json:"avatar"`                                  // 头像地址
	CreatedTime time.Time `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`             // 创建时间
	UpdatedTime time.Time `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`             // 更新时间
	State       int32     `gorm:"column:state;not null;comment:状态：1 启用 0 删除" json:"state"`                   // 状态：1 启用 0 删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
